services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir app"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis
    ports:
      - 6379:6379